export const jobposting = [
  {
    company: "Scribble Data",
    position: "Lead Engineer",
    experience: "5+ years",
    rating: "4.1",
    location: [
      "Kolkata",
      "Mumbai",
      "New Delhi",
      "Hyderabad/Secunderabad",
      "Pune",
      "Chennai",
      "Bangalore/Bengaluru",
    ],
    requirements: ["Backend", "Publishing"],
    posted_days_ago: 3,
    salary: "Not Disclosed",
    job_description: [
      "Scribble Data customers trust them with their data and the outputs and expect cutting-edge tools and thought processes. The product is at the center of the relationship with customers. We work smart, invest in tools and tech that are on the cutting edge of advanced analytics, and package all that we ve learnt about efficiency and data mileage into our products.",
      "As a Lead Engineer, you will work on extending functionality for Hasper. Your role will also include delivering working systems atop Hasper for Scribble s customers with high attention-to-detail ensuring trust, robustness, performance, and ease of use. Your responsibilities will include:",
      "- Develop high-performance data processing systems.",
      "- Develop and deploy robust, distributed, scalable, near real-time, data processing infrastructure that can support various downstream applications including reporting, analytics, user intelligence, machine learning, and decision support.",
      "- Incorporate customer feedback and new asks from customers into ongoing deliverables.",
      "- Accept nothing less than top-quality code and think in terms of code reviews, unit, integration, end-to-end tests in a fast-moving development environment, delivering incremental value daily.",
      "- Track and research emerging trends as well as competitors, thereby creating feedback loops for the product team.",
    ],
    requirements_and_skills: {
      requirements: [
        "5+ years industry experience in backend development",
        "Fluency in Python; you know the language and its quirks, not having just written scripts.",
        "Strong command of SQL.",
        "Strong understanding of computer science concepts (OOD, algorithm design, data structures, algorithms, execution, and memory optimization).",
        "Strong software engineering skills, system-level thinking, and problem-solving ability paired with the love to build and ship robust code.",
        "Experience developing and publishing APIs using web services.",
        "Strong communication and collaboration skills to work with stakeholders from different backgrounds.",
        "Bachelors/Masters in Computer Science.",
      ],
      skills_that_will_give_you_an_edge: [
        "Having built a product at a start-up.",
        "Experience in building data infrastructure / systems for data workflow management.",
        "Experience in full-stack development.",
        "Experience working in data-heavy applications",
        "Fluency with Pandas",
        "Experience using at least some among distributed storage (e.g. S3), serverless architecture (e.g. Lambda), streaming data (e.g. Kafka), and scalable search (e.g. Elasticsearch).",
        "Experience with big data technologies like map-reduce, NoSQL, Spark, HBase, and Hive.",
        "Experience with data security protocols and data access controls.",
      ],
    },
    product_technology_stack: {
      languages: ["Python", "SQL"],
      data_science_libraries: ["pandas", "numpy", "scikit-learn", "spacy"],
      deep_learning_frameworks: ["Tensorflow", "Keras", "PyTorch"],
      other_tools: ["R", "Matlab"],
    },
    additional_information: {
      Primarily_remote_work: true,
      Work_culture:
        "A work culture that helps you innovate and evolve continuously",
      Opportunity:
        "A chance to shape the future of ML, marrying it with generative AI",
      Domain: "Financial services domain that is career defining",
      Does_this_sound_like_you: [
        "You like adventure and have a stomach for learning and unlearning every day",
        "You are excited by powering up a whole generation of upcoming data applications",
        "You dream big and believe that hard problems need streamlined systems and massive amounts of data to tackle effectively",
        "You embrace uncertainty and can develop processes and systems to handle rapidly evolving requirements",
        "You have the discipline to take audacious goals and break down years-long roadmaps into near term deliverables that provide value to business stakeholders",
        "You enjoy educating your customers and team members about what it means to be data-oriented and cultivating engineering best practices",
        "You are comfortable selling to customers (not a biggie)",
        "You have a sense of humour",
      ],
    },
    role_details: {
      role: "Blockchain Quality Assurance Engineer",
      industry_type: "Software Product",
      department: "Engineering - Software & QA",
      employment_type: "Full Time, Permanent",
      role_category: "Quality Assurance and Testing",
      education: {
        UG: "Any Graduate",
        PG: "Any Postgraduate",
      },
      key_skills: [
        "Backend",
        "Publishing",
        "Machine learning",
        "Data structures",
        "MATLAB",
        "Analytics",
        "Financial services",
        "SQL",
        "Python",
      ],
    },
  },
];
